### ISSUE TITLE
Toll Semi's...

### ISSUE THREAD

**Issue by winde2000** [BROADACRESADMIN/BROADACRES16xMAPFS17-SEASONSMOD#4]
The Toll Semi's issued with the start of the map are not recognized by the placeable repair shop. I don't know if this is a known issue or intended to be this way or what but there I have told you about it.

Thanks for such an awesome map Ben and guys.

**Comment by BROADACRES16xFS17MAP** [comment]
I havent used that mod so unsure. Do they work if you purchase a new one.

**Comment by winde2000** [comment]
the placeable workshop is part of the vanilla game I thought, and yes I bought a road train semi and it had no issues with that,

**Comment by BROADACRES16xFS17MAP** [comment]
So is it a placeable workshop that you are using or is it the in game one installed in the map? Placeable's are separate mods all together. Might need to explain it a little more please.

**Comment by winde2000** [comment]
alright, the workshop at the store recognizes them, but the one you can buy under placeables doesn't, I tried to save time by setting up a workshop over where I was farming. No luck.

**Comment by BROADACRES16xFS17MAP** [comment]
I'm not aware of the placeable so may need to get in contact with there developer. If the map one works then it must be an issue with the placeable mod.
